# SPDX-License-Identifier: Apache-2.0
version: 2.1

orbs:
    docker: circleci/docker@0.5.0

setup-environment: &setup-environment
  machine:
    image: ubuntu-1604:201903-01
  resource_class: large
  working_directory: /home/circleci/go/src/github.com/Vijaypunugubati/fabric

install-packages: &install-packages
  - run: sudo apt-get update && sudo apt-get install -qq -y gcc libtool make

install-e2e-packages: &install-e2e-packages
  - run: sudo apt-get update && sudo apt-get install -qq -y gcc libtool make openjdk-8-jdk
  
install-go: &install-go
  - run: wget -qO- https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz | sudo tar -xvz -C /usr/bin

add-java-repo: &add-java-repo
  - run: sudo add-apt-repository ppa:openjdk-r/ppa

pull-binaries: &pull-binaries
  - run:
      command: |
        cd $working_directory || exit
        for IMAGES in releaseclean release; do
          make $IMAGES; done

#### Filters for ensuring builds only run on specific branches ####

filter-pr-only: &filter-pr-only
  filters:
    branches:
      ignore:
        - develop
        - QA

jobs:    
  byfn-eyfn:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      WORKSPACE: /home/circleci/go/src/github.com/Vijaypunugubati/fabric-samples
      # BASE_DIR:  go/src/github.com/hyperledger/fabric-samples
    steps:
      - <<: *add-java-repo
      - <<: *install-e2e-packages
      - <<: *install-go
      - <<: *pull-binaries
      - run:
          name: BYFN-EYFN
          command: |
            git clone -b master https://github.com/hyperledger/fabric-samples $WORKSPACE
            cd $WORKSPACE || exit
            cp -r $working_directory/home/circleci/project/fabric/release/linux-amd64/bin/ .
            git checkout master
          no_output_timeout: 60m

workflows:
  version: 2.1
  fabric:
    jobs:
      - byfn-eyfn
