# SPDX-License-Identifier: Apache-2.0
version: 2.1

orbs:
    docker: circleci/docker@0.5.0

setup-environment: &setup-environment
  machine:
    image: ubuntu-1604:201903-01
  resource_class: large
  working_directory: /home/circleci/project

install-packages: &install-packages
  - run: sudo apt-get update && sudo apt-get install -qq -y gcc libtool make

install-e2e-packages: &install-e2e-packages
  - run: sudo apt-get update && sudo apt-get install -qq -y gcc libtool make openjdk-8-jdk
  
install-go: &install-go
  - run: wget -qO- https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz | sudo tar -xvz -C /usr/bin

add-java-repo: &add-java-repo
  - run: sudo add-apt-repository ppa:openjdk-r/ppa

pull-fabric-artifacts: &pull-fabric-artifacts
  - run:
      command: |
        docker version
        docker-compose version
        for IMAGES in baseos peer orderer ccenv tools nodeenv javaenv ca; do
          docker pull nexus3.hyperledger.org:10001/hyperledger/fabric-$IMAGES:amd64-latest; done

pull-thirdparty: &pull-thirdparty
  - run:
      command: |
        for IMAGES in couchdb kafka zookeeper; do
          docker pull hyperledger/fabric-$IMAGES:amd64-0.4.15; done

pull-binaries: &pull-binaries
  - run:
      command: |
        cd $working_directory || exit
        for IMAGES in release-clean release; do
          make $IMAGES; done

jobs:    
  sdk-java-tests:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      WD: /home/circleci/project/fabric-sdk-java
      # BASE_DIR:  go/src/github.com/hyperledger/fabric-samples
    steps:
      - <<: *add-java-repo
      - <<: *install-e2e-packages
      - <<: *install-go
      - <<: *pull-fabric-artifacts
      - <<: *pull-thirdparty
      - run:
          name: SDK-JAVA-TESTS
          command: |
            git clone -b master https://github.com/hyperledger/fabric-sdk-java $WD
            cd $WD || exit
            export GOPATH=$WD/src/test/fixture
            cd $WD/src/test
            chmod +x cirun.sh
            source cirun.sh
          no_output_timeout: 60m

workflows:
  version: 2.1
  fabric:
    jobs:
      - sdk-java-tests
